require "plugins"
require "user.options"
require "user.keymaps"
require "user.colorscheme"
require "user.colorizer"
require "user.lualine"
require "user.autopairs"
require "user.nvim-tree"
require "user.lsp"
require "user.cmp"
require "user.gitsigns"
-- require "user.vimwiki"
